//
// Created by flori on 22/11/2019.
//

#ifndef SERVER_SHAEREDIMPORT_H
#define SERVER_SHAEREDIMPORT_H

enum CallStatus {
    CREATE, READ, READ_CALLED, PROCESS, FINISH
};

#endif //SERVER_SHAEREDIMPORT_H
